image: ubuntu:bionic

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt-get -y install
            cmake pkg-config cppcheck libogre-1.9-dev libglew-dev libfreeimage-dev doxygen ruby-ronn freeglut3-dev libxmu-dev libxi-dev curl git mercurial  g++-8
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
          - gcc -v
          - g++ -v
          - gcov -v
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git
          - cd lcov
          - make install
          - cd ..
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b gz11
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition tools
          - hg clone http://bitbucket.org/ignitionrobotics/ign-tools
          - cd ign-tools
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # SDFormat
          - hg clone http://bitbucket.org/osrf/sdformat -b gz11
          - cd sdformat
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition math
          - hg clone http://bitbucket.org/ignitionrobotics/ign-math -b gz11 
          - cd ign-math
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition common
          - hg clone http://bitbucket.org/ignitionrobotics/ign-common -b gz11
          - cd ign-common
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition msgs
          - hg clone http://bitbucket.org/ignitionrobotics/ign-msgs -b gz11
          - cd ign-msgs
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition transport
          - hg clone http://bitbucket.org/ignitionrobotics/ign-transport -b gz11 
          - cd ign-transport
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition rendering
          - hg clone http://bitbucket.org/ignitionrobotics/ign-rendering -b gz11 
          - cd ign-rendering
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition sensors
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage -DDRI_TESTS=FALSE
          - make -j4 install
          - make test
