image: ubuntu:bionic

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt update
          - apt-get -y install
            cmake pkg-config cppcheck libogre-1.9-dev libglew-dev libfreeimage-dev doxygen ruby-ronn freeglut3-dev libxmu-dev libxi-dev curl mercurial lcov
          - sh tools/code_check.sh
          # Ignition dependencies
          - apt-get -y install
            libignition-msgs2-dev
            libignition-tools-dev
            libsdformat6-dev
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b c++17
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition math
          - hg clone http://bitbucket.org/ignitionrobotics/ign-math -b gcc8_c++17
          - cd ign-math
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition common
          - hg clone http://bitbucket.org/ignitionrobotics/ign-common -b bionic
          - cd ign-common
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition msgs
          - hg clone http://bitbucket.org/ignitionrobotics/ign-msgs -b proto3
          - cd ign-msgs
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition transport
          - hg clone http://bitbucket.org/ignitionrobotics/ign-transport -b proto3_bionic
          - cd ign-transport
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition rendering
          - hg clone http://bitbucket.org/ignitionrobotics/ign-rendering -b bionic
          - cd ign-rendering
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition sensors
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=coverage -DDRI_TESTS=FALSE
          - make -j4 install
          - make test
